electionmodel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("model.urls"))
]

model/urls.py
from django.urls import path

from . import views

app_name = "model"
urlpatterns = [
    path("constituency/<str:constituency_id>/", views.constituency, name="constituency"),
    path("addresults/", views.addResults, name="addresults"),
    path("", views.index, name="main"),
]

model/models.py
from django.db import models

class Parties(models.TextChoices):
    CON = 'Con', 'Conservative and Unionist Party'
    LAB = 'Lab', 'Labour Party'
    LD = 'LD', 'Liberal Democrats'
    SNP = 'SNP', 'Scottish National Party'
    GRN = 'Grn', 'Green Party'
    REF = 'Ref', 'Reform UK'
    PC = 'PC', 'Plaid Cymru'
    WPB = 'WPB', 'Workers Party of Britain'
    SDP = 'SDP', 'Social Democratic Party'
    UKIP = 'UKIP', 'UK Independence Party'
    ALBA = 'Alba', 'Alba Party'
    IND = 'Ind', 'Independent'
    OTH = 'Oth', 'Other'

class Projection(models.Model):
    detailed = models.BooleanField(default=False)
    winner = models.CharField(max_length=4, choices=Parties.choices)
    con = models.FloatField(blank=True, null=True)
    lab = models.FloatField(blank=True, null=True)
    ld = models.FloatField(blank=True, null=True)
    ref = models.FloatField(blank=True, null=True)
    grn = models.FloatField(blank=True, null=True)
    snp = models.FloatField(blank=True, null=True)
    pc = models.FloatField(blank=True, null=True)
    min = models.FloatField(blank=True, null=True)

class Result(models.Model):
    winner = models.CharField(max_length=4, choices=Parties.choices)
    con_votes = models.IntegerField(blank=True, null=True)
    lab_votes = models.IntegerField(blank=True, null=True)
    ld_votes = models.IntegerField(blank=True, null=True)
    snp_votes = models.IntegerField(blank=True, null=True)
    grn_votes = models.IntegerField(blank=True, null=True)
    ref_votes = models.IntegerField(blank=True, null=True)
    pc_votes = models.IntegerField(blank=True, null=True)
    wpb_votes = models.IntegerField(blank=True, null=True)
    sdp_votes = models.IntegerField(blank=True, null=True)
    ukip_votes = models.IntegerField(blank=True, null=True)
    alba_votes = models.IntegerField(blank=True, null=True)
    ind_votes = models.IntegerField(blank=True, null=True)
    oth_votes = models.IntegerField(blank=True, null=True)
    total_votes = models.IntegerField()

class Constituency(models.Model):
    class Regions(models.TextChoices):
        NORTH_EAST = 'NE','North East'
        NORTH_WEST = 'NW','North West'
        YORKSHIRE = 'Y','Yorkshire and the Humber'
        WEST_MIDLANDS = 'WM','West Midlands'
        EAST_MIDLANDS = 'EM','East Midlands'
        SOUTH_WEST = 'SW','South West'
        SOUTH_EAST = 'SE','South East'
        LONDON = 'L','London'
        EAST = 'E','East of England'
        SCOTLAND = 'S','Scotland'
        WALES = 'W','Wales'
    
    name = models.CharField(max_length=64, unique=True, verbose_name='Constituency Name')
    id = models.CharField(max_length=9, primary_key=True)
    region = models.CharField(max_length=2, choices=Regions.choices, verbose_name='Region')
    winner2019 = models.CharField(max_length=4, choices=Parties.choices, verbose_name='2019 Winner')
    age_under_25 = models.DecimalField(max_digits=4,decimal_places=1)
    age_25_34 = models.DecimalField(max_digits=4,decimal_places=1)
    age_35_49 = models.DecimalField(max_digits=4,decimal_places=1)
    age_50_64 = models.DecimalField(max_digits=4,decimal_places=1)
    age_over_65 = models.DecimalField(max_digits=4,decimal_places=1)
    immigrant = models.DecimalField(max_digits=4,decimal_places=1)
    white = models.DecimalField(max_digits=4,decimal_places=1)
    religion_christian = models.DecimalField(max_digits=4,decimal_places=1)
    religion_islam = models.DecimalField(max_digits=4,decimal_places=1)
    religion_hindu = models.DecimalField(max_digits=4,decimal_places=1)
    religion_other = models.DecimalField(max_digits=4,decimal_places=1)
    base_con = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_lab = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_ld = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_ref = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_grn = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_snp = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_pc = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    base_min = models.DecimalField(max_digits=4,decimal_places=3, blank=True, null=True)
    basic_projection = models.OneToOneField(Projection, related_name='basic_projections', on_delete=models.SET_NULL, blank=True, null=True)
    detailed_projection = models.OneToOneField(Projection, related_name='detailed_projections', on_delete=models.SET_NULL, blank=True, null=True)
    result = models.OneToOneField(Result, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = 'constituency'
        verbose_name_plural = 'constituencies'

class TotalSeats(models.Model):
    party = models.CharField(max_length=4, choices=Parties.choices, unique=True)
    declared = models.IntegerField(default = 0, blank=True, null=True)
    projected = models.IntegerField(blank=True, null=True)

model/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, render
from django.core.management import call_command
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from django.conf import settings
from django import forms
from .models import Constituency, TotalSeats, Result
from .stats import baseVoteshare,resultVotes,projectionVoteshare,doBasicProjection, doDetailedProjection

def index(request):
    constituency_list = Constituency.objects.order_by("name")
    party_totals = TotalSeats.objects.order_by("-projected")
    overall_result = {"winner": party_totals[0].party, "majority": 2*party_totals[0].projected-650}
    context = {"constituency_list": constituency_list, "party_totals": party_totals, "overall_result": overall_result}
    return render(request, "models/index.html", context)

def constituency(request, constituency_id):
    constituency = get_object_or_404(Constituency, pk=constituency_id)
    if constituency.result:
        projection = resultVotes(constituency.result)
        pr_winner = constituency.result.winner
    else:
        if (constituency.detailed_projection) and settings.USE_DETAIL:
            projection = projectionVoteshare(constituency.detailed_projection)
            pr_winner = constituency.detailed_projection.winner
        elif constituency.basic_projection:
            projection = projectionVoteshare(constituency.basic_projection)
            pr_winner = constituency.basic_projection.winner
        else:
            projection = baseVoteshare(constituency)
            pr_winner = max(projection, key=projection.get)
    context = {"constituency": constituency, "projection": projection, "pr_winnner": pr_winner}
    return render(request, "models/constituency.html", context)

class ResultForm(forms.Form):
    constituency = forms.ModelChoiceField(queryset=Constituency.objects.all(), widget=forms.Select(attrs={'class': 'constituency-dropdown'}))
    con_votes = forms.IntegerField(label='Conservative Votes', min_value=0, required=False)
    lab_votes = forms.IntegerField(label='Labour Votes', min_value=0, required=False)
    ld_votes = forms.IntegerField(label='Lib Dem Votes', min_value=0, required=False)
    snp_votes = forms.IntegerField(label='SNP Votes', min_value=0, required=False)
    grn_votes = forms.IntegerField(label='Green Votes', min_value=0, required=False)
    ref_votes = forms.IntegerField(label='Reform UK Votes', min_value=0, required=False)
    pc_votes = forms.IntegerField(label='Plaid Cymru Votes', min_value=0, required=False)
    wpb_votes = forms.IntegerField(label='WPB Votes', min_value=0, required=False)
    sdp_votes = forms.IntegerField(label='SDP Votes', min_value=0, required=False)
    ukip_votes = forms.IntegerField(label='UKIP Votes', min_value=0, required=False)
    alba_votes = forms.IntegerField(label='Alba Votes', min_value=0, required=False)
    ind_votes = forms.IntegerField(label='Independent Votes', min_value=0, required=False)
    oth_votes = forms.IntegerField(label='Other Party Votes', min_value=0, required=False)

def check_admin(user):
   return user.is_superuser

@user_passes_test(check_admin)
def addResults(request):
    if request.method == "POST":
        form = ResultForm(request.POST)
        if form.is_valid():
            party_capitalisations = {'con': 'Con', 'lab': 'Lab', 'ld': 'LD', 'ref': 'Ref', 'grn': 'Grn', 'snp': 'SNP', 'pc': 'PC', 'wpb': 'WPB', 'alba': 'Alba', 'ukip': 'UKIP', 'sdp': 'SDP', 'ind': 'Ind', 'oth': 'Oth'}
            result = {k: v for k,v in form.cleaned_data.items() if k != "constituency"}
            constituency = form.cleaned_data["constituency"]
            filtered_result = {k: v for k, v in result.items() if v != None}
            result["total_votes"] = sum(value for value in filtered_result.values())
            result["winner"] = party_capitalisations[max(filtered_result, key=filtered_result.get)[:-6]]
            new_result = Result(**result)
            new_result.save()
            constituency.result = new_result
            constituency.save()
            if (Constituency.objects.exclude(result__isnull=True).count() > 29) and settings.USE_DETAIL :
                doDetailedProjection()
            else:
                doBasicProjection()
            call_command("clean_projections")
            return HttpResponseRedirect(reverse("model:main"))
    else:
        form = ResultForm()
    return render(request, "models/resultentry.html", {'form': form})

model/templates/models/constituency.html
<!DOCTYPE html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% load static %}
    {% load custom_filters %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
    <h3>{{ constituency.get_region_display }}</h3>
    <h1>{{ constituency }}</h1>
    <h3 class="{{constituency.winner2019}}">Implied 2019 Winner: {{ constituency.get_winner2019_display }}</h3>
    {% if constituency.result %}
        <h3 class="{{pr_winnner}}">2024 Winner: {{ pr_winnner|long_party_name }}</h3>
        <h2>Detailed Result: </h2>
    {% else %}
        <h3 class="{{pr_winnner}}">Projected Winner: {{ pr_winnner|long_party_name }}</h3>
        <h2>Current Projection: </h2>
    {% endif %}
    <canvas id="ProjectionChart"></canvas>
    <script>
        var ctx = document.getElementById('ProjectionChart').getContext('2d')
        var electionChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for party in projection %}'{{ party|medium_party_name }}'{% if not forloop.last %}, {% endif %}{% endfor %}],
                datasets: [{
                    label: 'Vote Share (%)',
                    data: [{% for voteshare in projection.values %}'{{ voteshare }}'{% if not forloop.last %}, {% endif %}{% endfor %}],
                    backgroundColor: [{% for party in projection %}'{{ party|party_colour }}'{% if not forloop.last %}, {% endif %}{% endfor %}],
                }]
            },
            options: {
                scales :{
                    y: {
                        display: true,
                        beginAtZero: true,
                        title: {
                            display: true,
                            text: {% if constituency.result %}'Votes'{% else %}'Vote Share (%)'{% endif %}
                        }
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    },
                    tooltip: {
                        enabled: false,
                    },
                events: [],
               }
            }
        });
    </script>
<!---
    Projection:
    <table>
        {% for party, voteshare in projection.items %}
        <tr>
            <td>
                {{ party|medium_party_name }}
            </td>
            <td>
                {{ voteshare|floatformat:1 }}%
            </td>
        </tr>
        {% endfor %}
    </table>
-->
    Demographic information:
    <table>
        <tr>
            <td rowspan="5">Voter Age</td>
            <td>&lt;25</td>
            <td>{{ constituency.age_under_25 }}%</td>
        </tr>
        <tr>
            <td>25-34</td>
            <td>{{ constituency.age_25_34 }}%</td>
        </tr>
        <tr>
            <td>35-49</td>
            <td>{{ constituency.age_35_49 }}%</td>
        </tr>
        <tr>
            <td>50-64</td>
            <td>{{ constituency.age_50_64 }}%</td>
        </tr>
        <tr>
            <td>65+</td>
            <td>{{ constituency.age_over_65 }}%</td>
        </tr>
        <tr>
            <td colspan="2">Non-UK Born</td>
            <td>{{ constituency.immigrant }}%</td>
        </tr>
        <tr>
            <td colspan="2">White</td>
            <td>{{ constituency.white }}%</td>
        </tr>
        <tr>
            <td rowspan="4">Religion</td>
            <td>Christianity</td>
            <td>{{ constituency.religion_christian }}%</td>
        </tr>
        <tr>
            <td>Islam</td>
            <td>{{ constituency.religion_islam }}%</td>
        </tr>
        <tr>
            <td>Hinduism</td>
            <td>{{ constituency.religion_hindu }}%</td>
        </tr>
        <tr>
            <td>Other</td>
            <td>{{ constituency.religion_other }}%</td>
        </tr>
    </table>
    <!---context: {{constituency}},{{projection}},{{pr_winnner}}--->
</body>


model/templates/models/index.html
<!DOCTYPE html>
<head>
    {% load static %}
    {% load custom_filters %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
    <h2>Current Projection: {{ overall_result.winner|medium_party_name }} {% if overall_result.majority >= 0 %} Majority of {{overall_result.majority}} {% else %} {{overall_result.majority|negate}} short of a Majority {% endif %}</h2>
    <table id="Seat-Table">
        <tr>
            <td>Party</td>
            <td>Declared</td>
            <td>Projected</td>
        </tr>
        {% for party in party_totals %}
            <tr>
                <td class="{{ party.party }}">{{ party.party|medium_party_name }}</td>
                <td class="{{ party.party }}" style="text-align: right;">{{ party.declared }}</td>
                <td class="{{ party.party }}" style="text-align: right;">{{ party.projected }}</td>
            </tr>
        {% endfor %}
        </table>
    {% if user.is_staff %}
    <div id = "addresults">Click <a href="{% url 'model:addresults' %}">here</a> to add results</div>
    {% endif %}
    <h2>Click on a constituency to view details</h2>
    <div class="constituency-list">
        <ul>
            {% for constituency in constituency_list %}
                <li>
                    <a href="{% url 'model:constituency' constituency.id %}" class = "
                        {% if constituency.result %} 
                            {{ constituency.result.winner }}Won
                        {% elif constituency.detailed_projection %} 
                            {{ constituency.detailed_projection.winner }}
                        {% elif constituency.basic_projection %}
                            {{ constituency.basic_projection.winner }}
                        {% else %} 
                            {{ constituency.winner2019 }}
                        {% endif %}
                    ">
                        {{constituency.name}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    Based on information from <a href="https://commonslibrary.parliament.uk/constituency-boundary-review-data-for-new-constituencies/">House of Commons Library</a>, 
    <a href="https://yougov.co.uk/politics/articles/49809-second-yougov-2024-election-mrp-shows-conservatives-on-lowest-seat-total-in-history">YouGov</a>,
    <a href="https://www.ipsos.com/en-uk/uk-opinion-polls/ipsos-election-mrp">Ipsos</a>,
    <a href="https://www.survation.com/survation-mrp-update-labour-set-to-become-the-largest-party-in-scotland/">Survation</a>,
    <a href="https://www.focaldata.com/blog/focaldata-prolific-uk-general-election-mrp">Focaldata</a>,
    <a href="https://www.moreincommon.org.uk/general-election-2024/mrp-19-june-2024/">More in Common</a>,
    <a href="https://www.electoralcalculus.co.uk/homepage.html">Electoral Calculus</a>,
    and various other sources of <a href="https://en.wikipedia.org/wiki/Opinion_polling_for_the_2024_United_Kingdom_general_election#National_poll_results">voting intention polls</a>
    including <a href="https://en.wikipedia.org/wiki/Opinion_polling_for_the_2024_United_Kingdom_general_election#Constituency_polling">individual consituency polls</a> where recent polling was available.
</body>

model/templates/models/resultentry.html
<!DOCTYPE html>
<head>
    {% load static %}
    {% load custom_filters %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
    <h1>Submit Election Result</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button><button type="reset">Reset</button>
    </form>
    <script>
        $(document).ready(function() {
            $('.constituency-dropdown').select2({
                placeholder: 'Select a constituency',
                allowClear: true
            });
        });
    </script>
</body>